version: 0.2
phases:
  install:
    commands:
      - echo install step...
  pre_build:
    commands:
      - echo logging in to AWS ECR...
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 962804699607.dkr.ecr.us-west-2.amazonaws.com
  build:
    commands:
      - echo build Docker image on `date`
      - docker build -t FROM node:13.12.0-alpine .
      - docker tag public.ecr.aws/docker/library/node:16.18.1-alpine:latest 962804699607.dkr.ecr.us-west-2.amazonaws.com/repo-vijd:latest
  post_build:
    commands:
      - echo build Docker image complete `date`
      - echo push latest Docker images to ECR...
      - docker push 962804699607.dkr.ecr.us-west-2.amazonaws.com/repo-vijd:latest
